export const NOTE_TYPES = {
  TEXT: "TEXT_TYPE",
  LIST: "LIST_TYPE",
  IMAGE: "IMAGE_TYPE",
  MUSIC: "MUSIC_TYPE",
  VIDEO: "VIDEO_TYPE",
  PAINT: "PAINT_TYPE",
  HOME: "HOME_TYPE",
  BACK: "BACK_TYPE",
  FORWARD: "FORWARD_TYPE",
  COLOR: "COLOR_TYPE",
};